version: '3.7'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
    - 8080:80
    volumes:
    - type: bind
      source: ./web/html
      target: /usr/share/nginx/html